/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: fa6391dcc2d8450dbb580eba1af4f85b)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "OverseerAgent";
  }
  interface Env {
    AI: Ai;
    OverseerAgent: DurableObjectNamespace<import("./src/server").OverseerAgent>;
  }
}
interface Env extends Cloudflare.Env {}
