/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 33efd3b17229f92f32173efc2e9ad735)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "ChatAgent";
  }
  interface Env {
    AI: Ai;
    ChatAgent: DurableObjectNamespace<import("./src/server").ChatAgent>;
    GOOGLE_AI_API_KEY: string;
    MYBROWSER: Fetcher;
    GITHUB_CLIENT_ID?: string;
    GITHUB_CLIENT_SECRET?: string;
  }
}
interface Env extends Cloudflare.Env {}
