/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 33efd3b17229f92f32173efc2e9ad735)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server/index");
    durableNamespaces: "ChatAgent" | "BridgeManager";
  }
  interface Env {
    AI: Ai;
    ChatAgent: DurableObjectNamespace<import("./src/server/index").ChatAgent>;
    BridgeManager: DurableObjectNamespace<
      import("./src/server/index").BridgeManager
    >;
    DB: D1Database;
    GOOGLE_AI_API_KEY: string;
    ARK_API_KEY: string;
    MYBROWSER: Fetcher;
    AUTH_SECRET: string;
    GOOGLE_CLIENT_ID: string;
    GOOGLE_CLIENT_SECRET: string;
    GITHUB_CLIENT_ID?: string;
    GITHUB_CLIENT_SECRET?: string;
    SENTRY_DSN?: string;
    R2?: R2Bucket;
    OTP_KV: KVNamespace;
  }
}
interface Env extends Cloudflare.Env {}
