/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 89ca040d099f98a755fddd96ab6ed769)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "GatekeeperAgent";
  }
  interface Env {
    AI: Ai;
    GatekeeperAgent: DurableObjectNamespace<
      import("./src/server").GatekeeperAgent
    >;
  }
}
interface Env extends Cloudflare.Env {}
