/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 2047ae4254f3b36ea07e986b325326e9)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "CoordinatorAgent";
  }
  interface Env {
    AI: Ai;
    CoordinatorAgent: DurableObjectNamespace<
      import("./src/server").CoordinatorAgent
    >;
  }
}
interface Env extends Cloudflare.Env {}
