/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 92262d6426e30a0f8fcb405313d58e4e)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "PayMCP" | "PayAgent";
  }
  interface Env {
    MCP_ADDRESS: string;
    CLIENT_TEST_PK: string;
    PayMCP: DurableObjectNamespace<import("./src/server").PayMCP>;
    PAY_AGENT: DurableObjectNamespace<import("./src/server").PayAgent>;
  }
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<Cloudflare.Env, "MCP_ADDRESS" | "CLIENT_TEST_PK">
  > {}
}
