/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 3fbc1bcdb453a6798ef4ef2d2ab4634e)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "MyMCP" | "Chat";
  }
  interface Env {
    AI: Ai;
    MyMCP: DurableObjectNamespace<import("./src/server").MyMCP>;
    Chat: DurableObjectNamespace<import("./src/server").Chat>;
  }
}
interface Env extends Cloudflare.Env {}
