/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 8121b6d7eb2a7478d6548fa81b0c96cd)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "ResearchAgent";
  }
  interface Env {
    ResearchAgent: DurableObjectNamespace<import("./src/server").ResearchAgent>;
  }
}
interface Env extends Cloudflare.Env {}
