/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 33efd3b17229f92f32173efc2e9ad735)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server/index");
    durableNamespaces: "ChatAgent" | "TunnelRelay";
  }
  interface Env {
    AI: Ai;
    ChatAgent: DurableObjectNamespace<import("./src/server/index").ChatAgent>;
    TunnelRelay: DurableObjectNamespace<
      import("./src/server/index").TunnelRelay
    >;
    DB: D1Database;
    BUILTIN_LLM_PROVIDER: string;
    BUILTIN_LLM_BASE_URL: string;
    BUILTIN_LLM_API_KEY: string;
    BUILTIN_LLM_MODEL: string;
    ARK_API_KEY: string;
    SEARCH_API_KEY?: string;
    SEARCH_API_BASE_URL?: string;
    SEARCH_API_MODEL?: string;

    AUTH_SECRET: string;
    GOOGLE_CLIENT_ID: string;
    GOOGLE_CLIENT_SECRET: string;
    GITHUB_CLIENT_ID?: string;
    GITHUB_CLIENT_SECRET?: string;
    SENTRY_DSN?: string;
    ADMIN_SECRET?: string;
    R2?: R2Bucket;
    R2_PUBLIC: R2Bucket;
    OTP_KV: KVNamespace;
    ASSETS: Fetcher;
  }
}
interface Env extends Cloudflare.Env {}
