/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: placeholder)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "DynamicToolsAgent";
  }
  interface Env {
    AI: Ai;
    DynamicToolsAgent: DurableObjectNamespace<
      import("./src/server").DynamicToolsAgent
    >;
  }
}
interface Env extends Cloudflare.Env {}
