/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 847990f0e3209b10c8bd3daa833e5720)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "PayAgent";
  }
  interface Env {
    PAY_AGENT: DurableObjectNamespace<import("./src/server").PayAgent>;
  }
}
interface Env extends Cloudflare.Env {}
