/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: f3ee88c936514badd975f8b415669938)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "SandboxAgent";
  }
  interface Env {
    LOADER: WorkerLoader;
    AI: Ai;
    SandboxAgent: DurableObjectNamespace<import("./src/server").SandboxAgent>;
  }
}
interface Env extends Cloudflare.Env {}
