/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 81c67d75e8ffed01fabf250068c9389d)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "Codemode";
  }
  interface Env {
    LOADER: WorkerLoader;
    AI: Ai;
    OPENAI_API_KEY: string;
    HOST?: string;
    Codemode: DurableObjectNamespace<import("./src/server").Codemode>;
  }
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<Cloudflare.Env, "OPENAI_API_KEY">
  > {}
}
